services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./backend/data:/app/data
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.market-api.rule=Host(`api.market.yugakurniawan.com`)"
      - "traefik.http.routers.market-api.entrypoints=https"
      - "traefik.http.routers.market-api.tls=true"
      - "traefik.http.routers.market-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.market-api.loadbalancer.server.port=8000"

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=https://api.market.yugakurniawan.com
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.market-frontend.rule=Host(`market.yugakurniawan.com`)"
      - "traefik.http.routers.market-frontend.entrypoints=https"
      - "traefik.http.routers.market-frontend.tls=true"
      - "traefik.http.routers.market-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.market-frontend.loadbalancer.server.port=3000"

networks:
  coolify:
    external: true
